### PR TITLE
Added caching cards to stop duplicate sending messages.

### PR DESCRIPTION
**Pull request by vasjen**
FC25 update

### CODE REVIEW

**Comment by siewex** [comment]
Hello! I wanted to thank you for sharing this tool, but I have some questions with starting the script.
I have proxy (login, password, IP and port) and how I put it on appsettings.json, under "Proxy" section, how it will be correct? Why in code there are proxy:api and proxy:service? Which proxy should I use?
I have local MSSQL 2019, so how I run it on, where should I change settings for my DB? Why there are only DBPassword there?

**Comment by vasjen** [comment]
> Hello! I wanted to thank you for sharing this tool, but I have some questions with starting the script. I have proxy (login, password, IP and port) and how I put it on appsettings.json, under "Proxy" section, how it will be correct? Why in code there are proxy:api and proxy:service? Which proxy should I use? I have local MSSQL 2019, so how I run it on, where should I change settings for my DB? Why there are only DBPassword there?

Hello, Pluto!
The instructions in the README are outdated; I haven't updated them in a long time. In the current version, a database is neither required nor used.

Proxies are also not stored anywhere in the current version. I use the API from https://proxy.market/ to automatically obtain the purchased proxies. When the application starts, I contact the API, retrieve the proxy data, including the username and password, create an HttpClient for each proxy, and then proceed with the card search loop.

The service itself will soon be available on Telegram. I need to update the rules for searching elements because the structure of the futbin website has changed, and this needs to be taken into account.

**Comment by siewex** [comment]
Oh, now I understood. The proxy.market is really good service. I hope you'll update script and maybe instructions, if you want to. I will be waiting for this!
Thank you for clarification!

**Comment by zipperbo** [comment]
> > Hello! I wanted to thank you for sharing this tool, but I have some questions with starting the script. I have proxy (login, password, IP and port) and how I put it on appsettings.json, under "Proxy" section, how it will be correct? Why in code there are proxy:api and proxy:service? Which proxy should I use? I have local MSSQL 2019, so how I run it on, where should I change settings for my DB? Why there are only DBPassword there?
> 
> Hello, Pluto! The instructions in the README are outdated; I haven't updated them in a long time. In the current version, a database is neither required nor used.
> 
> Proxies are also not stored anywhere in the current version. I use the API from https://proxy.market/ to automatically obtain the purchased proxies. When the application starts, I contact the API, retrieve the proxy data, including the username and password, create an HttpClient for each proxy, and then proceed with the card search loop.
> 
> The service itself will soon be available on Telegram. I need to update the rules for searching elements because the structure of the futbin website has changed, and this needs to be taken into account.

when you update the code

**Pull request merged**
